function [RunData] = get_config_numbers(RunData)
%GET_CONFIG_NUMBERS Summary of this function goes here
%   Detailed explanation goes here
for i = 1:length(Rundata)
    RunData(i).ConfigNum = bin2dec([...
        num2str(RunData(i).CamberAngle == -10),...
        num2str(RunData(i).CamberAngle == 0),...
        num2str(RunData(i).CamberAngle == 10),...
        num2str(RunData(i).FlareAngle == 10),...
        num2str(RunData(i).FlareAngle == 20),...
        num2str(RunData(i).FlareAngle == 30),...
        num2str(RunData(i).FlareAngle == 30),...
        num2str(strcmp(RunData(i).MassConfig,'RollingRig_Free')),...
        num2str(strcmp(RunData(i).MassConfig,'RollingRig_Fixed')),...
        num2str(strcmp(RunData(i).MassConfig,'RollingRig_Removed'))]);
end
end

